# https://docs.docker.com/compose/compose-file
# docker-compose up
# docker-compose stop
# docker-compose down
version: '3'
services:
  # This starts a local PostgreSQL DB.
  db:
    image: postgres:11
    container_name: api-luks-zapi-db
    restart: always
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=api-luks-zapi-db
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - '.db/data:/var/lib/postgresql/data'
